### PR TITLE
New update for french translation

### PR DESCRIPTION
**Pull request by tl-pierre**
Hi, 
I have updated the file with the newest changes. I'm also trying to progress on the few sentences that I'm having difficulty with. 

By the way, it seems to me that there is a problem with the content of the variable `GUI_AR` (line 676) : 
`GUI_AR="Restore steamuser data from 'XXX' to 'YYY?"`
instead of
`GUI_AR="Restore steamuser data from 'XXX' to 'YYY'?"`

Thank you for your work @frostworx 😃

### CODE REVIEW

**Comment by frostworx** [comment]
Hey, @tl-pierre! Thank you for your continuous translations! I pushed two more lines meanwhile. Would you like to translate those too or should I resolve the conflicts manually?
Good catch with the `?` typo! Thanks for the hint! :)
PS: Oh, something just changed - did you already add the 2 new lines? :)

**Comment by frostworx** [comment]
Hehe, you did! Thanks a lot! (it still complains about conflicts, but can't be something big - let's see)

**Comment by frostworx** [comment]
Hm, you changed some translations (f.e. `DESC_RUN_GDB`) and I'm a bit confused now tbh how this should be resolved.
Would you mind to check it again? Sorry...

**Comment by tl-pierre** [comment]
Sorry I arrived at the wrong time haha
I'm pretty bad with git, do I delete this pull request and create a new one ? I think it would be easier ...

**Comment by frostworx** [comment]
Hehe, we have a bad timing :)
Just wanted to manually merge it, and you *might* have removed it in between.
Clicking the Merge pull request button now - maybe it is still here :)

**Comment by frostworx** [comment]
Yay, it seems to have worked!
Thanks you very much again! :)

**Pull request merged**
