### PR TITLE
Fix symlinks not generating when steamlibrary has spaces or the target directories are also links

### LINKED ISSUE #389: listAppManifests breaks when Steam Library contains spaces
The wiki says that stl will do the following when starting vortex:

> create and update symlinks for all found game config directories of all found games in the SteamUser directory

Can you clarify how this is supposed to work, as I have to manually symlink `My Games` and `%LOCALAPPDATA%`  to get bethesda games to work. I'm assuming either I'm doing something wrong in my setup or the _“create and update symlinks”_ feature is incomplete?

#### Expected behaviour

I would expect that running `steamtinkerlaunch vortex start` would scan the installed games to see which are compatible with vortex and create the necessary links from vortex's WINEPREFIX to the relevant game(s) WINEPREFIX(s).

Perhaps the wiki note referrs to _other_ symlinks 

----

I have the following symlinks on my system (all manually created):

```
    ~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/AppData/Local/FalloutNV
 -> ~/.config/steamtinkerlaunch/compatdata/Fallout New Vegas/pfx/drive_c/users/steamuser/Local Settings/Application Data/FalloutNV

    ~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Fallout4
 -> ~/.config/steamtinkerlaunch/compatdata/Fallout 4/pfx/drive_c/users/steamuser/Local Settings/Application Data/Fallout4

    ~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/AppData/Local/Skyrim Special Edition
 -> ~/.config/steamtinkerlaunch/compatdata/Skyrim Special Edition/pfx/drive_c/users/steamuser/Local Settings/Application Data/Skyrim Special Edition/

    ~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/Documents/My Games/FalloutNV
 -> ~/.config/steamtinkerlaunch/compatdata/Fallout New Vegas/pfx/drive_c/users/steamuser/My Documents/My Games/FalloutNV

    ~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/Documents/My Games/Fallout4
 -> ~/.config/steamtinkerlaunch/compatdata/Fallout 4/pfx/drive_c/users/steamuser/My Documents/My Games/Fallout4

    ~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/Documents/My Games/Skyrim Special Edition
 -> ~/.config/steamtinkerlaunch/compatdata/Skyrim Special Edition/pfx/drive_c/users/steamuser/My Documents/My Games/Skyrim Special Edition/
```

(Well, actually I just link `My Games` to `~/Games` in all my WINEPREFIXes, but it's effectively the same, I still link all the APPDATA directories as above, for now):

```
    ~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/users/steamuser/Documents/My Games
 -> ~/Games

```

Additional screenshot for reference:

Vortex Symlinks

----

#### Sidenote

I noticed that Steam uses `Local Settings/Application Data` while stl/vortex uses `AppData/Local`. 
Also, Steam uses `My Documents/My Games` while stl/vortex uses `Documents/My Games`...
I'm guessing that each WINEPREFIX may have been initially created using different proton versions/configs? It doesn't seem to have caused an issue anyhow, just pointing out that they aren't using the same directory structure.

### PR DESCRIPTION
**Pull request by MattSturgeon**
The first commit fixes `vortex list-supported` not being initialised properly. The second commit fixes `listAppManifests` not supporting steam libraries with whitespace in the path (e.g. `~/Games/Steam Library`). Fixes #389 

EDIT: the third commit ensures `setModGameSyms` correctly discovers symlink targets when the target is itself a link (or a child of a link).

<details><summary><strong>original comments</strong></summary>

I'm marking this as a draft though, because (for me at least) this doesn't entirely fix the symlink issue. Probably because I have other symlinks setup manually in the game `compatdata`s, I'm assuming something in the code doesn't play nicely with creating symlinks that point through other symlinks.

For instance, I have `Documents/My Games` symlinked in each of my game `compatdata`s, and no symlinks were generated pointing to anything in `Documents/My Games`... A similar story with my Fallout 4 appdata:

image

</details>

### CODE REVIEW

**Comment by frostworx** [comment]
Thanks for the contribution, very appreciated!
Sounds like your missing symlinks are caused by readlink somewhere, which might require additional (or less) parameters to see your follow up symlinks.

**Comment by MattSturgeon** [comment]
Looks like my symlink problems are in `setModGameSyms`. In particular, the `find` commands being piped into the `while read -r` loops scanning for directories in the game `compatdata`s. These commands need to be modified to follow symlinks and to scan for symlinks to directories. Something like `find -L "$SRCPFX/$DRCU/$STUS/$DOCS/$MYGAMES" -mindepth 1 -maxdepth 1 \( -type d -o -type l -xtype d \)` should do the trick. 🤞

**Comment by frostworx** [comment]
Alternatively _(not tested)_ it should work as well to add a symlink check in the function `prepModGameSym`, which is called by every while loop in `setModGameSyms`
Edit: nope, I thought `type d` also finds symlinks pointing to dirs, which it doesn't :(

**Comment by frostworx** [comment]
`-mindepth 1 -maxdepth 1 -xtype d -a -type d -o -type l` does work

**Comment by MattSturgeon** [comment]
Hm, looks like specifying `-o -type l -xtype d` isn't actually necessary when the `-L` option is set.

We need to set `-L` anyway in-case the specified path to search is itself a symlink. Incidentally, it seems to make `-not -empty` behave better too...

```bash
$ tree
.
├── empty
├── link_to_empty -> empty
├── link_to_not_empty -> not_empty
└── not_empty
    └── content

4 directories, 1 file
```

```bash
# This is what's in the code right now... A little verbose:
$ find -L . -mindepth 1 -maxdepth 1 -not -empty '(' -type d -o -type l -xtype d ')'
./not_empty
./link_to_not_empty

# -L -type d seems to work rather well...
$ find -L . -mindepth 1 -maxdepth 1 -not -empty -type d
./not_empty
./link_to_not_empty

$ find . -mindepth 1 -maxdepth 1 -not -empty -type d
./not_empty

# -type l doesn't seem to support -not -empty
$ find . -mindepth 1 -maxdepth 1 -not -empty -type l -xtype d
./link_to_not_empty
./link_to_empty

# -type l doesn't seem to match anything when -L is set:
$ find -L . -mindepth 1 -maxdepth 1 -not -empty -type l -xtype d

```

**Comment by frostworx** [comment]
Great and transparent work! Thanks a lot for the fix!

**Comment by frostworx** [comment]
oh, this breaks it completely for me. `shellcheck` has several warnings/errors in function `getBIF`

**Comment by frostworx** [comment]
I haven't reverted the whole merge, but disabled the getBIF function:
https://github.com/frostworx/steamtinkerlaunch/commit/eccc9f20789caf898bbf12cf4dd3246984161ce1

**Comment by frostworx** [comment]
just pushed a fix which seems to work

**Pull request merged**
