### PR TITLE
SteamTinkerLaunch → Steam Tinker Launch

### PR DESCRIPTION
**Pull request by Faalagorn**
Updated name in readme to match nice name from 81c8613ce8e438c1f8dd1da2a47f1569f2b7c1e7

### CODE REVIEW

**Comment by Faalagorn** [comment]
The name in wiki could also be updated while at it ;)

https://github.com/frostworx/steamtinkerlaunch/wiki

**Comment by frostworx** [comment]
heh, thx for the monster PR! :)
The wiki auto-fixes anyway when https://github.com/frostworx/steamtinkerlaunch/issues/176 merges.

**Comment by Faalagorn** [comment]
> heh, thx for the monster PR! :)
> The wiki auto-fixes anyway when #176 merges.

Hey, it's 200% bigger than the smallest PR I made! Thanks for a quick merge :D

**Comment by frostworx** [comment]
Hehe, it is a [close race](https://github.com/frostworx/steamtinkerlaunch/commits?author=Faalagorn) though :P

**Pull request merged**
