### PR TITLE
Implemented MO2 silent mode

### PR DESCRIPTION
**Pull request by zerodogg**
This successfully launches Fallout: New Vegas with mo2 in silent mode for me

### CODE REVIEW

**Comment by sonic2kk** [comment]
Holy heck!! Thank you so much for this!

I am shocked to be honest. I didn't think Silent mode would ever get implemented (I didn't even know if it was still possible with MO2).

I'm going to test later today 😄

**Comment by sonic2kk** [comment]
Worked for me with New Vegas (fresh install, one mod) and Oblivion (existing install, many mods). We need to expose an option to allow this on the UI, under the MO2 mode dropdown, but that can be done at a later time :-)

I will merge this soon. Thanks a ton for this!!

**Comment by sonic2kk** [comment]
Still new to pushing to other people's PRs, tried to bump the version to merge this. I think it's good now, although due to the rebase I'm now a co-author of the commit (sorry).

You'll still get full credit in the changelog, and also wanted to say in this comment that this PR is fully your own work, it's just because of git-weirdness that I am a "co"-author; all this work is yours, not mine :-)

<hr>

This is ready to merge. Thank you a lot for your contribution!

**Comment by sonic2kk** [comment]
On the squash-merge commit you're listed as the sole author (18fd5f3), awesome!! Nothing to worry about then it seems :-) 

Credit has also been given for your work on the changelog! I will update the wiki to note that Silent Mode is now implemented, and push a change to add `silent` as a ModOrganizer 2 mode to the UI.

**Comment by zerodogg** [comment]
Cheers :)

**Pull request merged**
