### PR TITLE
update obs-vkcapture to obs-gamecapture

### PR DESCRIPTION
**Pull request by zany130**
https://github.com/frostworx/steamtinkerlaunch/issues/530

### CODE REVIEW

**Comment by frostworx** [comment]
what is this PR supposed to do? can't see any useful effect. Is it supposed to be complete.
more information please

**Comment by sonic2kk** [comment]
I believe it's meant to replace `obs-vkcapture` with `obs-gamecapture`, which accomplishes the same thing as `obs-vkcapture` but can detect if a program is OpenGL or Vulkan and from there it can internally select the right backend to record with.

From #530:
> also as <user> also wanted OpenGL capture I tried replacing `obs-vkcapture` with `obs-gamecapture` which automatically selects the correct one depending if the game is OpenGL or Vulkan seems to work here I'll post a PR shortly.

**Comment by frostworx** [comment]
I thought so, but the PR does nothing effectively. That's why I asked if it is supposed to be complete.

edit: I.e: the string "obs-gamecapture" does not occur even once in the PR.
And even if it did, I'd like to know where the program could be found.

**Comment by zany130** [comment]
Wdym?

 I changed the internal variable `OBSVK`to `OBSCAP` as it no longer just Vulkan capture.

And i changed `obs-vkcapture` to `obs-gamecapture` so it can work with OpenGL and Vulkan 

I tested these changes in Witcher enhanced edition using WINED3D (so OpenGl) and DXVK (so Vulkan) obs was able to see and capture the game both times

**Comment by frostworx** [comment]
> And i changed `obs-vkcapture` to `obs-gamecapture` so it can work with OpenGL and Vulkan

where?

and what is `obs-gamecapture` and where is its project page?

**Comment by sonic2kk** [comment]
I believe this line changes it:

https://github.com/frostworx/steamtinkerlaunch/pull/562/files#diff-77c6d4bb1bf7c1988ff5a068c856b6c24e113663f2e61cb3a2c98723c0fafc04R59

And the project page is the same as `obs-vkcapture`, under the usage section: https://github.com/nowrep/obs-vkcapture#Usage

**Comment by frostworx** [comment]
wtf! when I open the https://github.com/frostworx/steamtinkerlaunch/pull/562/commits
I only see 

besides the other correct variable renames.
thanks for clarification. Sorry, but of course, I wouldn't have asked otherwise 🤔

**Comment by zany130** [comment]
Yeah in the first push i forgot to change the actual value of the variable to `obs-gamecapture` I immediately pushed a second commit to fix that and update the lang files

**Comment by frostworx** [comment]
hah, excellent. thanks for the heads up and thanks for a great new feature! *merging* immediately! 😀

**Comment by zany130** [comment]
NP sorry about the confusion anyway something I didn't do in this PR Is remove the check for if we are using wine and if so disable  `obs-gamecapture` 

here https://github.com/frostworx/steamtinkerlaunch/blob/de990bcf54c07780ac275d1d9558c1b45274b8ec/steamtinkerlaunch#L16684

Is this necessary ? I assumed the reason was because wine would use WINED3D (thus OpenGL) instead of DXVK (thus Vulkan) but that's not an issue with `obs-gamecapture` and the user might expect it to work only to realize it was disabled because they are using wine instead of proton

and secondly IDK if changing `OBSVKC` to `OBSCAP` might mess up existing configs with `OBSVK` at least from my testing it doesn't cause any problems

**Comment by frostworx** [comment]
I don't think that the valid renaming of the variable has a deeper impact, because the function is pretty new and probaby only a few game configs of very few people are affected.
Can't remember why I added the wine check, but I guess it had some reason. If someone wants it removed, I wouldn't care as well though :)

**Comment by frostworx** [comment]
Oh, you edited while replying: yes, might have been wine3d related indeed :D

**Comment by zany130** [comment]
yeah sorry I have a bad habit of pressing submit or whatever in mid thought and then I'm like "oh should of clarified this" LOL I try to put EDIT whenever possible but If I always did that you would just see edit everywhere lol, so I just try to edit as fast as I can and hope no one notices 😅

anyway yeah I think that can be removed as a user might want to capture a game that is run with pure wine, before it might have prevented the game from working or maybe just silently failed but, the new `obs-gamecapture` should be able to handle this and automatically switch to OpenGL mode.

**Comment by frostworx** [comment]
hehe, np 😀
[just removed](https://github.com/frostworx/steamtinkerlaunch/commit/286ce650e2cf3a1ceb6ec3749dd9b6dbb48daa39) the if-clause. thanks for suggesting 👍

**Pull request merged**
