### PR TITLE
Overhaul Readme

### PR DESCRIPTION
**Pull request by sonic2kk**
I've felt for a while that the Readme for SteamTinkerLaunch could do with a bit of an overhaul, namely in the following ways:

1. Make it clearer what SteamTinkerLaunch can do
2. Add an image of the SteamTinkerLaunch Main Menu (so new users know how it looks before installation)
3. Make it clearer how to install SteamTinkerLaunch on various different platforms and the caveats/associated information about the different installation methods (which I also attempted to do with my overhaul of the [Installation wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Installation)
4. General organization of the information, as SteamTinkerLaunch has grown a lot an overhaul of the wiki helps keep all the information about features organized, including organizing the Markdown headings which makes the table of contents a bit cleaner:

image
 
You can check out the new Readme [visually on my fork](https://github.com/sonic2kk/steamtinkerlaunch) which is probably better for review purposes.

This overhauled Readme mainly just organises existing information that was already on the Readme. I added a table with a list of what I thought were key features of SteamTinkerLaunch that aren't simply third party dependencies - So excluding things like GameScope and MangoHud which are separate programs that STL just configures. I'm very open to feedback on this list, but I asked myself the question, "What features would I tell Windows users migrating to Linux about?" The answers I came to were: Mods, SpecialK, ReShade and easy downloading of Custom Proton/Wine releases.

In fact, the whole mentality I took while writing the Readme was how best to advertise SteamTinkerLaunch to new users. If there was someone who just happened to stumble across STL, what would they want to see and know? What is the best way to "sell" SteamTinkerLaunch? I have friends who are waiting on Steam Decks and I know someone planning to switch to Linux in the near-future on a new PC, so in part these changes were inspired so that I could just send them the project link and they can see all of the information themselves.

I feel like the new design of the Readme helps a lot with showing the project off, while also linking out to additional resources on the wiki and upstream projects. If someone hadn't heard of ModOrganizer 2 for example, there is a link to the upstream project. I wanted to ensure the Readme to be clear, informative and still easy to follow.

I realise this is a very huge change, and not all of the changes here might be welcome. Don't be afraid to be nitpicky, and if the changes are totally undesired I can close this PR.

Thanks! :smile:

### CODE REVIEW

**Comment by zany130** [comment]
Wow I think you should be the official PR guy for steamtinkerlaunch lol your wiki and now readme contributions look  amazing nice 👍 Hopefully @frostworx has time when he pops back over here (no rush) to look at this and merge it (technically I think I have permissions to merge this but I want to wait on him) my first thought when I was reading your wiki is why not list more features but NVM that would get unwieldy and possible overwhelm the user (not to mention more work 🤣)

**Comment by sonic2kk** [comment]
Thank you for the kind words 😄 I do my best to help out with and promote STL where I can :-)

 Before merging though I was reading through my writeup again and there are a couple of changes I'd like to make:

1.  The instructions for adding SteamTinkerLaunch to the path seem like a bit of a copout to me now that I look at it. Having instructions on how to do this in the Installation wiki page is probably a good idea, so I might see about adding that to the wiki page somewhere, then in the readme section about using the SteamTinkerLaunch launch option we can point to the section of that on the wiki.
2. It may be possible to use SteamTinkerLaunch in a "non-root" way as pointed out in #548. I'd like to add this to the wiki and subsequently add it to this Readme. I guess it's similar to manual installation but there are extra steps with the language files, of course adding the STL script to the path, and symlinking STL to `compatibilitytools.d` manually.
3. I made a couple of typos I think and minor formatting issues I'd like to correct.

Should hopefully have those fixed in the very near future 😄

**Comment by sonic2kk** [comment]
Hmm, I noticed the repositories widget doesn't list the [Fedora package](https://copr.fedorainfracloud.org/coprs/capucho/steamtinkerlaunch/) (quite out of date but still worth mentioning, could bring attention to it to ask for an update) or the [Nobara](https://copr.fedorainfracloud.org/coprs/gloriouseggroll/game-utils/build/4763034/) package (less than a day old at the time of writing, but if the Fedora package isn't found by the widget I don't think the Nobara one will be either). They are both hosted on Fedora Copr which seems like a Fedora AUR of sorts? The repository had to be added separately but there is also a Pacstall package which the widget lists, and it has to be installed separately.

Ideally we'd like to advertise all the available packages but that's probably more up to whoever maintains that package widget. We could always add a section on the Readme saying more packages may be available, and add Fedora and Nobara under the Distro-Specific section of the Installation instructions.

**Comment by sonic2kk** [comment]
Dug a little deeper and it seems Repology doesn't support these packages, which is unfortunate (repology/repology-updater#745).

I suppose a solution going forward would be to amend the package management section of the wiki to include instructions for each package? Either way it seems like it could be kept out of the Readme, and the Readme also has a section where there may be other packages out in the wild, which should imply to users that the list of packages may not be exhaustive.

**Comment by sonic2kk** [comment]
Alright, I've made a few changes:

1. Fixed the typos that I could spot (if you spot any more please let me know!)
2. The Installation wiki now has instructions for installing on Fedora and Nobara through the Copr repositories under the "Distro-Specific" section, and now the Readme reflects that there may be additional distro package information available on the Installation Wiki.
3. The Installation wiki now has instructions for installing SteamTinkerLaunch locally (without root privileges) under the Manual Installation section, and so the Readme now reflects the two ways of installing SteamTinkerLaunch manually.
4. The Readme now points to the local installation guide for a loose guide on adding the SteamTinkerLaunch script to the `PATH`, hopefully making it clearer to users how to do it
    - Though I suspect anyone wanting to install manually and rootless is probably a more advanced user that, at the very least, should hopefully know how to look up adding variables to their shell's `PATH` variable :sweat_smile: Not to mention SteamTinkerLaunch should cover most of the mainstream Linux distributions now (Ubuntu, Mint, Pop!_OS, Arch, Manjaro, Fedora, Nobara, and SteamOS), with the only exception coming to mind being Debian (unless Pacstall supports Debian?). I think we're fine on this front, but if anyone has any suggestions to improve the guide for adding to path, I'm open to it!

This PR got a bit messy with the commits as I was just using GitHub's markdown editor to make the changes, but merging with squashing the commits should be fine as this is only the Readme. We don't need like 8 commits that are just amending some Markdown :smile:

**Comment by frostworx** [comment]
I blindly trust you, because any wiki change of you makes it better without nay doubt, @sonic2kk.
Thanks for your continued support both with PRs and with helping others! 👍

**Pull request merged**
