### PR TITLE
Fixes for Polish

### PR DESCRIPTION
**Pull request by Faalagorn**
Minor fixes for Polish that I found afterwards, there's probably more!

### CODE REVIEW

**Comment by frostworx** [comment]
Thanks a lot again! I removed several functions though and added multiple new ones though. Can't tell when changes are ready for commit, but just to let you know, that some translations might already disappear very soon

**Comment by Faalagorn** [comment]
> Thanks a lot again! I removed several functions though and added multiple new ones though. Can't tell when changes are ready for commit, but just to let you know, that some translations might already disappear very soon

Yeah, I noticed some strings are missing, I was curious how it'll apply to 5.0 but guess it can all be sorted out eventually, I'll be on lookout. :) Here's the ones I noticed missing when testing today:
screenshot_2021-05-01-173254
screenshot_2021-05-01-173144
screenshot_2021-05-01-173139
screenshot_2021-05-01-172916
screenshot_2021-05-01-172907
screenshot_2021-05-01-172120
screenshot_2021-05-01-171924


I'm in a middle of sending a PR for English fixes and some minor Polish ones I still find here and there anyway, hopefully they won't interfere too much.

**Comment by frostworx** [comment]
Would be nice if you would wait with further PRs, as it is a bit of trouble to keep them in sync with my offline language files. I hope you understand this. bh I do not 100% understand your screenshots :) f.e. protola was completely removed already, as it is no longer required.

**Comment by Faalagorn** [comment]
> Would be nice if you would wait with further PRs, as it is a bit of trouble to keep them in sync with my offline language files. I hope you understand this. bh I do not 100% understand your screenshots :) f.e. protola was completely removed already, as it is no longer required.

Yeah, sorry, I realized I was running on a non-git 4.0 version of stl before I switched to `-git` package in AUR. :) #230 was my last PR for now, especially as you stated on https://github.com/frostworx/steamtinkerlaunch/pull/230#issuecomment-830664329 you are working offline as well (I noticed that before in your 5.0 comments, but hopefully git itself as well as pletfhora of diff tools available will help in the process of merging down the line! :)

**Pull request merged**
