### PR TITLE
Interface translation update

### PR DESCRIPTION
**Pull request by IDeathByte**

### CODE REVIEW

**Comment by frostworx** [comment]
Please be so kind and remove the ".history" directory from your branch.
I do not want to remove it manually everytime when merging your request.

**Comment by IDeathByte** [comment]
hm i didn`t see it in my repo

**Comment by frostworx** [comment]
But it is in your pull request.
You see it when you "view the diff" here: 
https://github.com/frostworx/steamtinkerlaunch/pull/114/commits/ae6235236de25cf54a0188304ab046959f80c3e8

Maybe it helps if you explicitly make a 
`git rm -f .history`
in your checkout(?)

**Comment by IDeathByte** [comment]
very strange. i haven`t it in checkout too. ok i try again

**Pull request closed without merging**
