### PR TITLE
Added italian translation

### PR DESCRIPTION
**Pull request by Pyr0x1**
This referes to #89. It was a bit hard to translate some of the entries because many terms are very "specific" so I decided to keep them in the original language, I hope the translation is good enough. If it will be merged can you please add the `hacktoberfest-accepted` label to this PR? Thank you.

### CODE REVIEW

**Comment by frostworx** [comment]
Thank you very much for your help and time! :)

**Comment by Pyr0x1** [comment]
No problem 😁 can you please just add the `hacktoberfest-accepted` label to this Pull Request please?

**Comment by frostworx** [comment]
Oh of course sorry! I just woke up and I'm not completely ready yet :)
I just have to find out how to set a label, never did that before.

**Comment by frostworx** [comment]
yay! now more coffee ;)
Have a nice weekend!

**Comment by Pyr0x1** [comment]
Thank you, same to you 😁

**Comment by frostworx** [comment]
thanks!

**Pull request merged**
