### PR TITLE
[WIP] Add more game artwork paths to Non-Steam Game UI

### PR DESCRIPTION
**Pull request by sonic2kk**
## Overview
This PR adds the ability to set more game artwork (background, logo, boxart) when adding Non-Steam Games. It also has some minor formatting changes to the Add Non-Steam Game GUI.

image

The current file picker on Steam for Linux is tedious to use, so adding these paths manually can be really annoying. Being able to do it from a GTK file picker is a lot more user-friendly.

## Implementation
These files are set by copying them to `$STUIDPATH/config/grid` with appropriate names. This is where Steam reads them from if you set the manually, they aren't written to any VDF file from what I can see. Manually setting artwork for regular Steam games also writes them here.

Steam expects the files for the games to be named in a specific way.

- Background/Hero files are named `<app_id>_hero`
- Logos  are named `<app_id>_logo`
- Box art is named `<app_id>p`
- Small artwork is named `<app_id>` with no special suffix (this is the artwork that shows up when the game is the most recently played)

## Problems
This PR is marked as WIP because currently there's a big problem. The files are copied over to the correct folder with a set AppID, but **this AppID might be wrong**. When opening Steam after adding a shortcut, no game art shows up, and when you run the game, the AppID that shows up for the Proton prefix is different from the one that the files are given when they're copied over to the `grid` folder.

There should be a reliable way of doing this, as [Steam-Rom-Manager](https://github.com/SteamGridDB/steam-rom-manager) is able to do this when adding Non-Steam shortcuts (I've verified this myself by using it on Steam Deck). I'm not sure how it does this though. The AppID might only change when the game runs with Proton, which may mean we have to set STL as the compatibility tool (**if** it's an EXE) and *then* update the AppID? 

Aside from the language files, this is the main thing holding this PR back. I decided to open the PR in its current state to figure out a good way of getting the AppID. If we do find a way, we might have to move the artwork copying to the bottom of `addNonSteamGame`, so I'll try to remember to do that too :sweat_smile: 

## Todo
- [ ] Get Steam AppID
- [ ] Probably change the wording of the strings in the language files to use better terms, e.g. "Background/Hero" and better explain what the small artwork is
- [ ] Update all language files

## Considerations
I have no idea how this works with Flatpak, so I'm hoping however `$STUIDPATH` is gotten works on Flatpak too :sweat_smile: 

No rush on merging this or anything, but it's something I was tinkering around with and wanted to get some guidance on further implementation. Thanks! :smile:

### CODE REVIEW

**Comment by sonic2kk** [comment]
I was having a look around and I found a (abandoned?) project that seems to be able to work out the AppID for Non-Steam games. From a Steam thread, this looks like the relevant part of the code: https://github.com/scottrice/Ice/blob/7130b54c8d2fa7d0e2c0994ca1f2aa3fb2a27ba9/ice/steam_grid.py#L49-L64

The `bit_by_bit` method it uses is here: https://github.com/scottrice/Ice/blob/7130b54c8d2fa7d0e2c0994ca1f2aa3fb2a27ba9/ice/crc_algorithms.py#L122-L149

I'm more confident that it's correct because it looks like something identical is being done in this `node-steam-shortcuts` library: https://github.com/Hafas/node-steam-shortcuts/commit/d8888f153a96db864fe8e64089cfc0675880f511

I'm not totally sure how STL generates the AppID, I'm pretty sure it's this block of code but I'm not sure how it works and so not sure if it matches what's in the code above:

```bash
NOSTAIDRHX="$(printf "%03x%03x%02x\n" $((RANDOM%4096)) $((RANDOM%4096)) $((RANDOM%256)))"
NOSTAID="$(hex2dec "$NOSTAIDRHX")"
NOSTAIDHX="\x$(awk '{$1=$1}1' FPAT='.{2}' OFS="\\\x" <<< "$NOSTAIDRHX")"
```

So it seems there's a way to calculate the AppID for Non-Steam Games based likely on its path? Although it should be said that when STL runs it correctly gets the AppID for the Non-Steam game...

**Comment by sonic2kk** [comment]
I found the code that Steam ROM Manager uses to generate its AppIDs: https://github.com/SteamGridDB/steam-rom-manager/blob/dc8500ebe7df467f310b1d36fbc93b44494169be/src/lib/helpers/steam/generate-app-id.ts

This code indicates that the AppID used to find artwork in Big Picture (which is also what the Deck Game Mode uses!) and the desktop client are different. I was able to confirm this on desktop, as the IDs I set for HoloCure's images didn't work in Steam Big Picture. The icons worked though, as they're set in the  `shortcuts.vdf` file.

Seems there is a bit more work to be done on this PR!

**Comment by frostworx** [comment]
Hats off for your attempt to add this! 👍
I do not remember in detail what I did, but you're right
```
NOSTAIDRHX="$(printf "%03x%03x%02x\n" $((RANDOM%4096)) $((RANDOM%4096)) $((RANDOM%256)))"
NOSTAID="$(hex2dec "$NOSTAIDRHX")"
NOSTAIDHX="\x$(awk '{$1=$1}1' FPAT='.{2}' OFS="\\\x" <<< "$NOSTAIDRHX")"
```
generates the AppID used for the non-steam game. This still works fine, so it should be safe to simply use that generated ID _(no need to look for it)_ (IIRC originally the AppID is partially created from the CRC of the game name - this didn't work for me and apparently also is not required)

The compatdata path for non-steam games always are in `~/.local/share/Steam/steamapps/compatdata/` which makes it pretty easy to find it for a game if required.
Please let me know if you need anything else or I misunderstood something :)

**Comment by frostworx** [comment]
Just added manually a `3748286522_logo.jpg` for a testing non-steam game with stl generated appid `3748286522` and it was ignored _(didn't restart steam, maybe required?)_, but picking a png logo from steam generated a `3748286522_logo.png` in the same directory which was shown immediately. tl;dr: 
maybe a
- steam restart
- steam steam://resetcollections
- png image
is required to actually see the selected image _(?)_

**Comment by sonic2kk** [comment]
> *(didn't restart steam, maybe required?)*

*Usually* yeah you need to restart Steam when you put the images in the folder yourself. On one occasion only the background image showed up when I put the image in the folder manually, but this only happened on one occasion and I still can't reproduce it. Restarting Steam seems to make it show up though.

Picking the image from Steam gets it to show up immediately, I guess it refreshes somehow.

> png image

Sorry, I should've been clearer! I just used png as an example, Steam supports jpgs, pngs and gifs (some games even give you special animated gif boxart and such, Yakuza 0 has this). I read somewhere that Steam also supports tga images but I can't find that now so take that part with a grain of salt. I've personally tested JPGs, PNGs for game backgrounds, logos, boxart and the smaller box art, but I have only tested GIFs for the box art and smaller box art. I haven't (yet) tested gifs for logos or backgrounds, but they might be supported.

> This still works fine, so it should be safe to simply use that generated ID (no need to look for it)

That would be great if it works fine! I'll have to do some more tests then. But I'm curious for how this will affect Big Picture/Steam Deck, since according to the Steam ROM Manager code, it uses a different AppID. I'll have to manually test this I suppose, maybe by the following:
- Add a Non-Steam game via STL
- Manually set artwork in Desktop mode
- Manually set artwork in Big Picture and see what the AppID is, and if it's stored in a different folder.

> (IIRC originally the AppID is partially created from the CRC of the game name - this didn't work for me and apparently also is not required)

Yes, I believe it's created from the game path + game name, but I spent hours yesterday and I couldn't get it to match what Steam generates, so I gave up :sweat_smile: 

P.S. Just seen the branch has conflicts now, I'll resolve them after more tests if this feature is viable :slightly_smiling_face:

**Comment by frostworx** [comment]
Sorry, **I** should have been clearer 😀
What I meant is, that I hoped that providing a png instead of a jpg might skip the steam restart dependency.
It was just a wild guess and seems like it was wrong 🙄
Can't say anything about Big Picture mode, but I'd be surprised if it used a different SteamAppID for the corresponding game. I'd assume it stores its specific Big Picture mode pics using a specific suffix instead.

When adding a non-steam game using stl and adding artwork for it using Steam directly, the image name is using this auto-generated appid, so it works as expected.

As `steam steam://resetcollections` is required anyway to make a non-steam game available, it should just work to copy the picked pictures under the corresponding name, and they should be available afterwards.
Please let me know if you require anything else from my side, but I'd guess it should just work.

**Comment by sonic2kk** [comment]
Just an update that I haven't forgotten about this PR, I've been a little preoccupied with personal life, only having a little time to investigate into this and some other projects I'm working on unrelated to STL. Very sorry about that! If it's okay to leave this open I'll dig back into this ASAP :heart:

**Comment by frostworx** [comment]
No hurry and thanks for the heads up! Whatever you do have fun! :)

**Comment by sonic2kk** [comment]
>  Can't say anything about Big Picture mode, but I'd be surprised if it used a different SteamAppID for the corresponding game. I'd assume it stores its specific Big Picture mode pics using a specific suffix instead.

Steam-Rom-Manager has a specific separate function to generate this AppID, however Steam Big Picture seems to behave differently in my tests. I found [this Steam forum post]() which suggested the same as you, that Big Picture game art just has a different suffix (`appid_header.png`). But this didn't work in my tests, and it seems like Non-Steam Games in Big Picture get their art via the game icon. Changing the icon in Big Picture worked but it overwrote the initially set icon in the `shortcuts.vdf` file.

Honestly, I'm not sure it's worth spending much time at least in this PR for supporting Big Picture. It will probably get replaced by the Deck UI or something similar in future, and Big Picture is not very popular as far as I can see on the desktop.

> When adding a non-steam game using stl and adding artwork for it using Steam directly, the image name is using this auto-generated appid, so it works as expected.

Right, but it seems the AppID that STL generates when adding the game to Steam, and the AppID Steam uses when you manually set the game art from Steam, appear to be different. When using the changes I made in this PR, STL will copy over the game artwork with what should be the correct names (`appid_suffix`, preserving whatever the original file extension was). But this won't show up for me in Steam the last time I tested, even though I can see the files in `$STUIDPATH/config/grid`, so the code is coming them over, but the AppID set for them by STL and the AppID used by Steam appear to be different.

That's where the problems lie with this PR as far as I can tell. I'll have to do some more tests and see where exactly I left off, but this is the problem I was facing. SteamTinkerLaunch will correctly create, say `2468522275_hero.png`, but if you were to set the artwork for this game in Steam, it would create a file with a different AppID, say `5718166392_header.png` (entirely made up AppID). It _should_ be possible, somehow, to set these correctly, as Steam-Rom-Manager is able to do it, I've used it first-hand on Steam Deck with EmuDeck which creates shortcuts.

I'll try to dig back into this over the next few days but hope that clarifies the issue I believe this PR is facing. If this is fixed, this PR should be ready for a further review and hopefully after the conflicts are cleaned up, a merge :smile:

**Comment by frostworx** [comment]
sorry, for the late reply.
thanks for elaborating! I'm not sure that the AppID created by steam when adding artwork from Steam directly is made up, but instead would guess that Steam has a problem finding the made up AppID created by steamtinkerlaunch and therefore re-created the proper one the non-steam game should correctly have _(just guessing, but I think it would be a sane explanation for the weirtd behavior)_.
Or the other way around:
when adding a non-steam game directly in Steam and adding an artwork also from Steam, do the AppIDs of the game and its artwork match as expected? I'd guess yes, but who knows :)
If so, it seems like we indeed need the correct programmatically creation of the AppID and not only a hald guessed one.
I'll dig though my irc backlogs (if still available), because iirc I had some discussion about the AppID creation with the main steamdb dev once.

**Comment by sonic2kk** [comment]
Still tinkering around with this, and while looking around for info on AppIDs I found better names for the artwork, so I'll be renaming those:

- Icon: Shows up on Steam Deck when downloading games; shows up in Steam client as the icon beside the game on the lefthand side
- Hero: Long banner artwork when you're on a game's page in your library
- Logo: The game logo that appears overtop the hero artwork. On Steam Deck, this shows up in the "Steam" menu while in-game at the top (where it gives you options like Resume, Achievements, etc etc)
- Box Art: This is the tall rectangular artwork that shows up for a game in your library
- 10foot: This is the more square boxart that appears for your most recently played game.

This might not mean much until if and when I get the AppIDs thing sorted out. I'm still investigating and at some point I am determined to learn even for my own knowledge how this works! Sorry that this PR has been opened for so long with very little code changes - lots of research has gone on in the background as you might've gathered from the various PRs and discussions related to Steam AppIDs. Though I still understand it probably isn't very nice as a project maintainer to have just this one PR sitting idly open for a long time :sweat_smile: 

Work is still ongoing!

**Comment by sonic2kk** [comment]
So I'm very sorry to say that after quite a long time of researching, I've still come up short :sweat: I'm determined to figure this out one day, but that day may not be anytime soon. So I'm opting to close this PR, at least for now. 

The """issue""" with generating the Steam Shortcut AppID should be separate from this work. In other words, there should be a separate PR to fix the Steam Shortcut AppID generation, and *then* this PR should be reviewed separately. The logic in this PR should work if the AppID is generated correctly, I tested and the files were moved correctly, and I just changed the AppID in the file name and restarted Steam. That got it to set correctly.

The underlying AppID problem could be solved by one of the following: 
- Figuring out how to generate the same Shortcut AppID as the same one Steam sets
  - It seems like Steam ROM Manager [generates](https://github.com/SteamGridDB/steam-rom-manager/blob/master/src/lib/helpers/steam/generate-app-id.ts) and [writes out](https://github.com/SteamGridDB/steam-rom-manager/blob/master/src/lib/vdf-manager.ts#L173-L192) this AppID to the `shortcuts.vdf` file (using what looks like some custom code they made for managing VDF files). However I can't get their code or my Bash code to match what Steam generates, so I'm wondering if perhaps the way STL writes to the `shortcuts.vdf` file is not the same as how this program does it. Might be worth at some point trying to investigate how they write to it but that's a task for another day.
- Setting a custom AppID (I *highly* doubt this is possible based on my research here and in #550)
- Retrieving the AppID from somewhere (Steam updates the `shortcuts.vdf` file 

My money is on the first approach, I think it's worth looking at how Steam-ROM-Manager actually handles this in more detail - Though if they are able to write out this AppID I wonder if this opens up the possibility for setting custom ones 🧐

Many apologies for opening a PR on work I could not finish, I try to ensure a good standard for contributions to other peoples' work. I did a lot of research in this area though and did give it a good attempt, and have hopefully laid the groundwork for someone else in future to look into this. I realise this rightfully going to be very low priority, but the information is there for anyone in future that wishes to take up the mantle (perhaps future me if I feel like looking into AppIDs again :sweat_smile:)

Hopefully future PRs end up having more success!

**Comment by sonic2kk** [comment]
Well, past @sonic2kk, a future PR will have more success!

I figured out how Steam generates the Non-Steam Game AppIDs (or to be more precise, how it does *not*, but how we can set our own custom Non-Steam AppID), and was able to salvage much of this PR and re-integrate this functionality, now that we actually get the Non-Steam AppIDs. We also have a function for copying, moving, or linking Steam game artwork, so this was able to be re-used for this functionality (as well as its language strings!)

**Comment by frostworx** [comment]
great to see you still have fun with the project! have a nice weekend :)

**Pull request closed without merging**
