### PR TITLE
Fixes to English strings

### PR DESCRIPTION
**Pull request by Faalagorn**
Mostly case fixes and program name fixes, but there were some minor fixes as well, mostly found when making a Polish translation.

### CODE REVIEW

**Comment by frostworx** [comment]
Thanks for your contributions! **Very** appreciated! I'm going to merge this PR, after my offline work is committed, as it would be [a bit of trouble](https://github.com/frostworx/steamtinkerlaunch/pull/228#issuecomment-830659790) to keep it in sync with my current changes.

**Comment by frostworx** [comment]
Hey @Faalagorn
Just pushed [Steam Tinker Launch - 6.8-rc1 - Blood](https://github.com/frostworx/steamtinkerlaunch/issues/235) \o/
Would you mind rebasing your PR - there are multiple lines which are no longer used anymore.

Of course, it would be also great if you would also translate the new added lines into polish :)

**Comment by Faalagorn** [comment]
> Hey @Faalagorn
> Just pushed [Steam Tinker Launch - 6.8-rc1 - Blood](https://github.com/frostworx/steamtinkerlaunch/issues/235) \o/
> Would you mind rebasing your PR - there are multiple lines which are no longer used anymore.
> 
> Of course, it would be also great if you would also translate the new added lines into polish :)

Should be rebased now, I also included some fixes for the new lines. :) I also added new Polish lines with #237.

**Comment by frostworx** [comment]
Thanks a lot for this as well @Faalagorn! :)
With more people like you, it would make much more fun to keep on working on stl publically!

No idea why I started somewhere to write everything upper-case (maybe it looks better in the gui?).
Not sure with GameScope reverts though, iirc I've seen it written like this before, but why not? :)

**Comment by Faalagorn** [comment]
> With more people like you, it would make much more fun to keep on working on stl publically!

No worries, that's what open source projects are at after all. :)

> No idea why I started somewhere to write everything upper-case (maybe it looks better in the gui?).

Aren't you German? I got such impression from your writing when you left verbs in uppercase, that would explain it. I'm personally a title case person, especially as there's no such thing as title case in Polish really, the only verbs written with upper letter are names and places names, even book titles use sentence cases here.

As far as all caps goes, I prefer avoiding it, but if someone insist, I prefer using `text-transform` in HTML for it, I didn't dig into the code to see if something like this is possible. Don't count on it, but I might take a look at the code later on.
  
> Not sure with GameScope reverts though, iirc I've seen it written like this before, but why not? :)

I wasn't 100% sure either, might be something to think for later; if so I'll change it in Polish to match, but it seems that the all lowercase is used in the description here: https://github.com/Plagman/gamescope.

P.S. Whatever is decides, Wiki would need to be adjusted, but I might take a look later if I find some time.

**Comment by frostworx** [comment]
Hi there :)
Yeah I'm german, and you're right pretty much is written in uppercase in german. Anyway I know that most things are written lowercase and I usually do so, but since some months I started to write everything uppercase... :)

Thanks again for your friendly help! :)
I'll roll out v6.8 soon and will take a break from the project (yay, nature!) afterwards, but I mostly won't be too long away from the computer :)

**Pull request merged**
